# A-2_Q1-a.c  A-2_Q1-b.c  A-2_Q2-a.c  A-2_Q2-b.c  A-2_Q2-c1.c  A-2_Q2-c2.c  A-2_Q3.c  A-2_Q5.c
all: A-2_Q1-a  A-2_Q1-b  A-2_Q2-a  A-2_Q2-b  A-2_Q2-c1  A-2_Q2-c2  A-2_Q3  A-2_Q5

A-2_Q1-a: A-2_Q1-a.c
	gcc -o A-2_Q1-a A-2_Q1-a.c

A-2_Q1-b: A-2_Q1-b.c
	gcc -o A-2_Q1-b A-2_Q1-b.c

A-2_Q2-a: A-2_Q2-a.c
	gcc -o A-2_Q2-a A-2_Q2-a.c

A-2_Q2-b: A-2_Q2-b.c
	gcc -o A-2_Q2-b A-2_Q2-b.c

A-2_Q2-c1: A-2_Q2-c1.c
	gcc -o A-2_Q2-c1 A-2_Q2-c1.c

A-2_Q2-c2: A-2_Q2-c2.c
	# gcc -lm A-2_Q2-c2 math.h
	gcc -o A-2_Q2-c2 A-2_Q2-c2.c

A-2_Q3: A-2_Q3.c math.h
	gcc -o A-2_Q3 A-2_Q3.c

# A-1_Q4: A-2_Q4.c
#         gcc -o A-2_Q4 A-2_Q4.c

A-2_Q5: A-2_Q5.c
	gcc -o A-2_Q5 A-2_Q5.c
