# output: A-1_Q1.o A-1_Q3.o A-1_Q4.o A-1_Q5.o
# 	gcc A-1_Q1.o A-1_Q3.o A-1_Q4.o A-1_Q5.o -o output

# A-1_Q1.o: A-1_Q1.c 
# 	gcc -c A-1_Q1.c

# A-1_Q3.o: A-1_Q3.c
# 	gcc -c A-1_Q3.c

# A-1_Q4.o: A-1_Q4.c
# 	gcc -c A-1_Q4.c

# A-1_Q5.o: A-1_Q5.c
# 	gcc -c A-1_Q5.c

# clean:
# 	rm *.o output 
all: A-1_Q1 A-1_Q3 A-1_Q4 A-1_Q5 A-1_Q2 

A-1_Q1: A-1_Q1.c
	gcc -o A-1_Q1 A-1_Q1.c

A-1_Q2: A-1_Q2.c
	gcc -o A-1_Q2 A-1_Q2.c

A-1_Q3: A-1_Q3.c
	gcc -o A-1_Q3 A-1_Q3.c

A-1_Q4: A-1_Q4.c
	gcc -o A-1_Q4 A-1_Q4.c

A-1_Q5: A-1_Q5.c
	gcc -o A-1_Q5 A-1_Q5.c

 