all: 
	gcc -o fifo_p1.o fifo_p1.c
	gcc -o fifo_p2.o fifo_p2.c
	gcc -o message_queue_p1.o message_queue_p1.c
	gcc -o message_queue_p2.o message_queue_p2.c
	gcc -o socket_p1.o socket_p1.c
	gcc -o socket_p2.o socket_p2.c
clean:
	rm *.o